### ISSUE TITLE
Trying to train the model with 128*64 pixel images instead of 640*320 px images

### ISSUE THREAD

**Issue by viba98** [williamyang1991/TET-GAN#6]
Every time I try doing this, I get the error "ValueError: Expected more than 1 spatial element when training, got input size torch.Size([72, 512, 1, 1])". 

How do I fix this so the code can work to train images that are 128*64 pixels? Would training it only on L1 work?

**Comment by williamyang1991** [comment]
Can you provide the whole error information? With only a ValueError info, I have no idea what is wrong.

Have you specified the data size (wd, ht) when preparing your data?

https://github.com/williamyang1991/TET-GAN/blob/bdfca141fc14c5917fd9be8d2bc23870f9ad3288/src/utils.py#L103

**Comment by viba98** [comment]
I just did, I changed it to 64.

I now get this error:

<img width="930" alt="image" src="https://user-images.githubusercontent.com/32447352/189857631-e813b7f9-e02f-4d85-9ad2-78e15df5828b.png">


I also ran the code with wd and ht on this line as both 256 and 64 but received the same error. 

https://github.com/williamyang1991/TET-GAN/blob/bdfca141fc14c5917fd9be8d2bc23870f9ad3288/src/utils.py#L42

Also thank you for replying so quickly! :)

**Comment by williamyang1991** [comment]
I think I find the problem.
Since our model is based on pix2pix, the encoder will project a 256x256 image into a 8x8 feature map, and then in the sharing layer, the  rcb1 and rcb2 will further downsample it twice to a 2x2 feature map.

In your case, your input is 64x64, the encoder will map it to 2x2, and rcb1 will map it to 1x1, after padding, it becomes 3x3, but the conv kernal in rcb2 is 4x4, which is larger than the feature map. 

I think for your case, you need to modify the rcb1/rcb2/rdcb3/rdcb2/rdcb1 in the sharelayer to normal relu-conv-bn layers without any downsampling or upsampling.

**Comment by viba98** [comment]
That makes a lot of sense! Thank you so much, I fixed it with this :)
